site_dir: docs-site
site_name: 机器人调度系统文档 
repo_url: https://gitee.com/Jimmy-chen-zheng/robot-interface-demo.git
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: 深色模式
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 亮色模式


  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.image.zoom 
    - content.image.lightbox
    - toc.integrate           # 进入页面后，左侧显示该页的标题小目录（TOC）替代全站导航
    - navigation.footer
    - navigation.top          # ↑ 回到顶部浮动按钮（建议开）


nav:
  - index.md
  - overview.md
  - live-demo.md
  - config-nacos.md
  - observability.md
  - stability-sentinel.md
  - mq-async.md
  - docker-deploy.md
  - loadtest-jmeter.md
  - issues-rca.md

plugins:
  - i18n:
      docs_structure: suffix
      reconfigure_material: true
      languages:
        - locale: zh
          name: 中文
          default: true
          build: true
          site_name: 机器人调度系统文档
        - locale: en
          name: English
          build: true
          site_name: Robot Scheduling Docs
  - search:
      lang: [zh, en]


extra_css:              # ← 顶层键，放这里即可（顺序无所谓）
  - styles.css          # ← 文件在 docs/styles.css  
extra_javascript:
  - move-palette.js
extra:
  social:
    - icon: material/github
      link: https://github.com/JimmyZChen
      name: GitHub
    - icon: simple/gitee
      link: https://gitee.com/Jimmy-chen-zheng
      name: Gitee
    - icon: material/email
      link: mailto:chenzheng2024xm@163.com
      name: Email
    - icon: material/linkedin
      link: https://www.linkedin.com/in/jimmy-chen-74a8182b8/
      name: LinkedIn

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 1-2
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


